# Generated by Django 3.0.8 on 2020-07-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200709_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='toto@titi.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default='user', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='username', max_length=45),
            preserve_default=False,
        ),
    ]
