# Generated by Django 3.0.8 on 2020-07-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200709_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
    ]
